### ISSUE TITLE
predict function availability?

### ISSUE THREAD

**Issue by nietzschetmh** [nwfsc-timeseries/MARSS#14] opened 2019-05-15 13:38 UTC
It seems predict_marss and predict_marxss are already under development, when will these functions be released?

**Comment by eeholmes** [comment] 2019-08-03 21:01
I don't have a timeline for those yet. Determining how to specify the "new" data is not clear.  There are many different approaches I might take and I need to decide on an approach that will allow a wide variety of model and data types.

**Comment by eeholmes** [comment] 2019-12-01 21:32
Update: I am currently working on updating tidy.marssMLE which summarizes some of the calculations and concepts needed for the predict functions.  

What I have seen in texts using MARSS models to predict is not what I would call confidence or prediction intervals since the Fisher Information matrix never appears in those calculations. What is presented is what I would call the quantiles on X(t)|Y(t)=y(1),hat(Theta).  That is quite different than what is meant by a confidence interval which is related to the variance of \hat(\mu)-\mu (estimate of statistic relative to true value). In MARSS case this is
var_Y [ E[X(t)|Y(t),hat(Theta)]-X(t)|Y(t)=y(1),hat(Theta) ].

If you call predict on an lm object (linear regression) with new data and interval=confidence, you get the CIs on the expected value of y and that includes the info on the variance of \hat(\mu)-\mu.  For MARSS, I want predict to output something similar. I don't want just something equivalent to simulating from the estimated MARSS model. That's useful but not a confidence interval on fitted values.

This is however more complex for y since the fitted y is a random variable with 2 sources of variability: y = f(X(t)) and v(t), both X(t) and v(t) are random variables.  E[y(t)] is imprecise. Do you mean E_v[y], E_v[E_X[y]] or E_X[y].  The middle one is a point, the other 2 are still random variables.

**Comment by eeholmes** [comment] 2019-12-04 03:20
**Step 1 for predict function.**   I think I will tackle the easy problems first:

* One-step-ahead prediction which I already have coded in tidy.marssMLE
* Prediction past T, which is T+1, T+2, T+3, etc.  See pages 147-148 in Harvey 1989. It just involves running the Kalman filter forward for the required number of steps (page 148).

The harder problem of new data within 1:TT conditioned on the existing data, is an important problem 
* Did these new data come from this process?
* What can I say about the distribution of Y(t)|y(1,t)?  The distribution of Y(t) may be what I care about, but I only have one sample y(1,t). What can I say about all the other data that I didn't see?

For that problem, I think I should tackle the independent new data problem first. That should be straight-forward.

What gets tricky with that, is have to say something about the correlation (if any) between the new and old data. But what if they are not independent?  The math is actually straight-forward. The problem is how to specify what R structure you want without it being a big mess?  In fact, I think for that the user has to manually fix their R, add a row of NAs to y for the new data, and then run MARSShatyt() to get the ytT and OtT for that row.

**Comment by eeholmes** [comment] 2020-01-10 04:11
Update 1/9/2020

I ended up solving the harder problem first: new data within 1:TT conditioned on the existing data. After working on the update to Residuals.Rnw, I was able to see the solution fairly quickly.  
* The conditioning on existing data case has been added to EMDerivation in the section on 'Computing the expectations for the update equations'.
* Independent data is now in type="fitted.ytT" in tidy() and also in fitted().
* One-step-ahead prediction within 1:TT can be done with fitted(conditioning="t-1"). Available for observations and states.

**Some things to do**

* If you want to compare your one-step-ahead predictions to the actual data (or estimated) states, you need the innovations residuals.  I put those in Residuals.Rnw but have not added a function to return them. It's simple. I just haven't done it yet.  Does require some care to deal with degenerate variances properly (without throwing an error).
* Haven't tackled this yet. "Prediction past T, which is T+1, T+2, T+3, etc. See pages 147-148 in Harvey 1989. It just involves running the Kalman filter forward for the required number of steps (page 148)." I think I want to look at forecast() and see what that output looks like now. I think it was updated to tibble output.

**Comment by eeholmes** [comment] 2020-01-29 04:24
1/27/20 Update
* Added MARSSresiduals.tt1( ) for the one-step-ahead predictions

**To do**
* Prediction past T (see notes above)
* Assemble into predict( ) function
* Compare to predict( ) in **forecast** and **KFAS** packages. Maybe should look similar.
* Consider using forecast( ) for predicting past T. I don't really like what predict( ) does for linear models. It does both confidence and prediction intervals which is confusing (to me).

**Comment by eeholmes** [comment] 2020-02-22 03:52
2/16-21/2020 Update

Added a predict.marssMLE() and forecast.marssMLE() function. They act similarly except that forecast is for a forecast past the end of the data. But the main function for both is predict.marssMLE since then I can use the base predict generic. I don't want to require forecast just to have its forecast class generic.
* It is the prediction interval for independent data (iid data sets)
* You can pass in newdata, to use the fitted model on a new data set
* If you pass in newdata, you can set it to estimate x0
* forecasting I did the easy way by adding NAs to the end of the data set.

Added a plot function for class marssPredict, which for now is what predict.marssMLE() returns.
* Looks like plot.forecast from the forecast package, on purpose.

**To do**

*  Write the autoplot() function.
*  Lots more testing, esp on time-varying models and models with covariates.

**Comment by eeholmes** [comment] 2020-02-25 22:25
Version 3.10.13 released with predict.marssMLE() and forecast.marssMLE() functions.

**Closed by eeholmes** 2020-02-25 22:25 UTC
Labels: enhancement
